version: "3.7"

services:

  api:
    container_name: user-auth-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      DB_URL: jdbc:postgresql://user-auth-db:5432/user-auth
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  user-auth-db:
    container_name: user-auth-db
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=user-auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
